version: "3.9"

services:
  sugar-backend:
    build: ./
    command: ./wait-for-postgres.sh sugar-db ./main
    ports:
      - "8080:8080"
    depends_on:
      - sugar-db
    environment:
      - DB_HOST=sugar-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=sugar-db
      - POSTGRES_PASSWORD=postgres

  sugar-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sugar-db
    restart: unless-stopped
