version: "3.9"

services:
  sugar-backend:
    build: ./
    command: ./sugar-backend
    ports:
      - "8080:8080"
    depends_on:
      - sugar-db
    environment:
      - POSTGRES_PASSWORD=postgres

  sugar-db:
    restart: unless-stopped
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sugar-db
